version: '3'
services:
  app:
    container_name: chatgpt-web
    image: thlearn/chatgpt-web
    ports:
      - 6666:3002
    environment:
      # api地址：
      # OPENAI_API_KEY: 
      # OPENAI_API_BASE_URL: 

      # 反向代理，可选
      API_REVERSE_PROXY: http://PandoraNext:8181/xxxx/backend-api/conversation
      OPENAI_ACCESS_TOKEN: 

      #密码
      AUTH_SECRET_KEY: 
      OPENAI_API_MODEL: gpt-4
      # gpt-4, gpt-4-0314, gpt-4-0613, gpt-4-32k, gpt-4-32k-0314, gpt-4-32k-0613, gpt-3.5-turbo-16k, gpt-3.5-turbo-16k-0613, gpt-3.5-turbo, gpt-3.5-turbo-0301, gpt-3.5-turbo-0613, text-davinci-003, text-davinci-002, code-davinci-002
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: 0
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
    networks:
      - mynetwork
networks:
  mynetwork:
    external: true

